server:
  port: 2030
spring:
  application:
    name: hrm-page
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm-page?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: cw99626!
mybatis-plus:
  mapper-locations: classpath:com/fx/hrm/mapper/*Mapper.xml
  type-aliases-package: com.fx.hrm.domain,com.fx.hrm.query