server:
  port: 2010
spring:
  application:
    name: hrm-sysmanage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm-sys-manage
    username: root
    password: cw99626!
mybatis-plus:
  mapper-locations: classpath:com/fx/hrm/mapper/*Mapper.xml
  type-aliases-package: com.fx.hrm.domain,com.fx.hrm.query